<?php
$search="";
$title = 'My albums';
 $this->headTitle($title);
 $url_order = 'ASC';
if ($order_by == 'title')
    $url_order = ($order == 'ASC') ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = ($order == 'ASC') ? 'DESC' : 'ASC';
if(!empty($search_by))
    $search=$search_by;
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>  </p>
 <?php
$form  = $this->form;
$form->setAttribute(($this->url('album', array('order_by' => $order_by, 'order' => $url_order))),$search);
$form->prepare();
echo $this->form()->openTag($form);
foreach ($form as $element) :
    ?>
    <div class="control-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <div class="controls">
            <?php
            echo $this->formElement($element);
            if ($this->formElementErrors($element)):
                ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                <?php
            endif;
            ?>
        </div>
    </div>
<?php
endforeach;
echo $this->form()->closeTag();
?>
<table class="table">
 <tr>
     <th><a href="<?php echo $this->url('album', array('order_by' => 'title', 'order' => $url_order), array('query' => $search)); ?>">Title<?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
     <th><a href="<?php echo $this->url('album', array('order_by' => 'artist', 'order' => $url_order),array('query' => $search)); ?>">Artist<?php if ($order_by == 'artist'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
     <th>Action</th>
     <th>&nbsp;</th>
 </tr>
  <?php foreach ($this->paginator as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
  <?=
  $this->paginationControl(
     $this->paginator,       
     'sliding',
     'partial/paginator.phtml',
     array('order_by' => $order_by, 'order' => $order, 'search_by' => $search,'pageAction' => $pageAction)
 )
        ?>
